# Generated by Django 4.1.5 on 2023-01-18 01:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('valence', models.FloatField()),
                ('year', models.IntegerField()),
                ('accousticness', models.FloatField()),
                ('artists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('danceability', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('energy', models.FloatField()),
                ('explicit', models.IntegerField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('release_date', models.CharField(max_length=10)),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('playlists', models.ManyToManyField(to='spotifydb.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='spotifydb.song'),
        ),
    ]
