# Generated by Django 4.1.3 on 2023-01-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotifydb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artists",
        ),
        migrations.RemoveField(
            model_name="song",
            name="explicit",
        ),
        migrations.RemoveField(
            model_name="song",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="song",
            name="name",
        ),
        migrations.RemoveField(
            model_name="song",
            name="popularity",
        ),
        migrations.RemoveField(
            model_name="song",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="song",
            name="year",
        ),
    ]
